# 使用官方 Ubuntu 作為基礎映像
FROM ubuntu:latest

# 更新套件清單並安裝基本軟體
RUN apt-get update && \
    apt-get install -y openssh-server apache2 openssl sudo

# 建立使用者及設定權限
RUN useradd -m K999 && \
    usermod -aG sudo K999 && \
    echo 'K999:congragulation' | chpasswd

# 檢查並建立 SSH 服務
RUN if [ ! -f /etc/ssh/sshd_config ]; then \
        apt-get install -y openssh-server; \
    fi

# 啟動 SSH 服務
RUN service ssh start

# 檢查並建立 HTTP 服務
RUN if [ ! -f /etc/apache2/apache2.conf ]; then \
        apt-get install -y apache2; \
    fi

# 啟動 Apache2 服務
RUN service apache2 start

# 檢查並建立 HTTPS 服務
RUN if [ ! -f /etc/apache2/sites-available/default-ssl.conf ]; then \
        apt-get install -y openssl && \
        a2enmod ssl && \
        a2ensite default-ssl && \
        service apache2 restart; \
    fi

# 檢查並建立 sudo 函數
RUN if ! grep -q "#includedir /etc/sudoers.d" /etc/sudoers; then \
        echo "#includedir /etc/sudoers.d" >> /etc/sudoers; \
    fi

# 漏洞設定
RUN useradd Allin && \
    echo 'Allin:admin' | chpasswd && \
    mkdir /home/Allin && \
    echo "some random text" > /home/Allin/user.txt

# 網站設定
COPY website.sh /home/K999/website.sh
RUN chown K999:K999 /home/K999/website.sh && \
    chmod +x /home/K999/website.sh

# 提權設定
RUN echo "root's flag" > /root/root.txt && \
    echo "ALL ALL=(ALL) NOPASSWD: /bin/cp" >> /etc/sudoers

# 啟動腳本以保持容器運行
CMD tail -f /dev/null
